# Default values for marcstreeterdev-registry
# This is a YAML-formatted file.

# Global configuration
global:
  environment: development

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: registry-app
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 3000

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: registry.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits
resources:
  configMapName: marcstreeterdev-registry-config
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m

# Environment variables
env: []

# Development configuration (only mode supported)
dev:
  enabled: true
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 200m
